server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spyglass
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: none

logging:
  level:
    com:
      spyglass: trace
    org:
      springframework:
        web: debug
        security: debug

jwt:
  secret: ${JWT_SECRET}